// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKDQBo6COq7R26tI0JVB8oLqXA5V1uydo',
    appId: '1:712710781374:web:2d597080b15c48ed6821ef',
    messagingSenderId: '712710781374',
    projectId: 'thestudentbudget-d60b2',
    authDomain: 'thestudentbudget-d60b2.firebaseapp.com',
    storageBucket: 'thestudentbudget-d60b2.appspot.com',
    measurementId: 'G-298FBM74NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6XgQbzBvJUvBJnB2_mw-gJmURT9x9Zag',
    appId: '1:712710781374:android:fe72a925367828a86821ef',
    messagingSenderId: '712710781374',
    projectId: 'thestudentbudget-d60b2',
    storageBucket: 'thestudentbudget-d60b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLoo1l5MMUyfeYwz1Xd8MJ7HZVl-xXnKs',
    appId: '1:712710781374:ios:5036cbb5d255d5016821ef',
    messagingSenderId: '712710781374',
    projectId: 'thestudentbudget-d60b2',
    storageBucket: 'thestudentbudget-d60b2.appspot.com',
    iosClientId: '712710781374-pmabp16ps6tgm7aetsmsd9so01aic0nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.thestudentbudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLoo1l5MMUyfeYwz1Xd8MJ7HZVl-xXnKs',
    appId: '1:712710781374:ios:5036cbb5d255d5016821ef',
    messagingSenderId: '712710781374',
    projectId: 'thestudentbudget-d60b2',
    storageBucket: 'thestudentbudget-d60b2.appspot.com',
    iosClientId: '712710781374-pmabp16ps6tgm7aetsmsd9so01aic0nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.thestudentbudget',
  );
}
